"""recriação das tabelas

Revision ID: 06662af11c74
Revises: 5604b677f992
Create Date: 2025-11-08 22:38:28.655566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06662af11c74'
down_revision = '5604b677f992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reles', schema=None) as batch_op:
        batch_op.alter_column('limite_individual',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_column('saldo_minimo_para_desligar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo_minimo_para_desligar', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.alter_column('limite_individual',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
