"""Criação das tabelas iniciais

Revision ID: 3455ca3b9738
Revises: 06662af11c74
Create Date: 2025-11-10 00:08:47.364561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3455ca3b9738'
down_revision = '06662af11c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultima_alteracao_manual', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reles', schema=None) as batch_op:
        batch_op.drop_column('ultima_alteracao_manual')

    # ### end Alembic commands ###
