"""Criação das tabelas iniciais

Revision ID: 5454cec8a07e
Revises: 3455ca3b9738
Create Date: 2025-11-10 01:06:38.462201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5454cec8a07e'
down_revision = '3455ca3b9738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultima_sincronizacao_esp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('bloqueado_para_sincronizacao', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reles', schema=None) as batch_op:
        batch_op.drop_column('bloqueado_para_sincronizacao')
        batch_op.drop_column('ultima_sincronizacao_esp')

    # ### end Alembic commands ###
