"""recriação das tabelas

Revision ID: 5604b677f992
Revises: 1ebeefd59c7a
Create Date: 2025-11-08 22:13:21.982694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5604b677f992'
down_revision = '1ebeefd59c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modo_automatico', sa.Boolean(), nullable=True))
        batch_op.drop_column('desligar_automatico')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desligar_automatico', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('modo_automatico')

    # ### end Alembic commands ###
