"""Criação das tabelas iniciais

Revision ID: 79fcae7bdac5
Revises: 8b972e278eb6
Create Date: 2025-11-20 01:36:20.319317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79fcae7bdac5'
down_revision = '8b972e278eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo_baixo_limite', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.drop_column('saldo_baixo_limite')

    # ### end Alembic commands ###
