"""Criação das tabelas iniciais

Revision ID: 8b972e278eb6
Revises: cd25375d93ab
Create Date: 2025-11-19 02:48:04.208052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b972e278eb6'
down_revision = 'cd25375d93ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smtp_server', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('smtp_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('email_sender', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('email_password', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.drop_column('email_password')
        batch_op.drop_column('email_sender')
        batch_op.drop_column('smtp_port')
        batch_op.drop_column('smtp_server')

    # ### end Alembic commands ###
