"""Criação das tabelas iniciais

Revision ID: cd25375d93ab
Revises: 5454cec8a07e
Create Date: 2025-11-19 01:38:26.213047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd25375d93ab'
down_revision = '5454cec8a07e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_saldo_baixo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('alert_consumo_pico', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('alert_reles_desligados', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('alert_pzem_offline', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('alert_erro_sistema', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_browser', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_frequency', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('telegram_bot_token', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.drop_column('telegram_bot_token')
        batch_op.drop_column('telegram_chat_id')
        batch_op.drop_column('email_frequency')
        batch_op.drop_column('notify_browser')
        batch_op.drop_column('alert_erro_sistema')
        batch_op.drop_column('alert_pzem_offline')
        batch_op.drop_column('alert_reles_desligados')
        batch_op.drop_column('alert_consumo_pico')
        batch_op.drop_column('alert_saldo_baixo')

    # ### end Alembic commands ###
